sim-cmd: Fix readline function declaration compiler warnings
These readline functions were causing the warnings:

    ../or1ksim/sim-cmd.c: In function 'initialize_readline':
    ../or1ksim/sim-cmd.c:799:36: error: assignment to 'char ** (*)(const char *, int,  int)' from incompatible pointer type 'char ** (*)(void)' [-Wincompatible-pointer-types]
      799 |   rl_attempted_completion_function = sim_completion;
	  |                                    ^
    ../or1ksim/sim-cmd.c:787:8: note: 'sim_completion' declared here
      787 | char **sim_completion ();
	  |        ^~~~~~~~~~~~~~
    ../or1ksim/sim-cmd.c: At top level:
    ../or1ksim/sim-cmd.c:810:1: error: conflicting types for 'sim_completion'; have 'char **(char *, int,  int)'
      810 | sim_completion (char *text, int start, int end)
	  | ^~~~~~~~~~~~~~
    ../or1ksim/sim-cmd.c:787:8: note: previous declaration of 'sim_completion' with type 'char **(void)'
      787 | char **sim_completion ();
	  |        ^~~~~~~~~~~~~~
    ../or1ksim/sim-cmd.c: In function 'sim_completion':
    ../or1ksim/sim-cmd.c:820:44: error: passing argument 2 of 'rl_completion_matches' from incompatible pointer type [-Wincompatible-pointer-types]
      820 |     matches = rl_completion_matches (text, command_generator);
	  |                                            ^~~~~~~~~~~~~~~~~
	  |                                            |
	  |                                            char * (*)(void)
    In file included from ../or1ksim/sim-cmd.c:39:
    /usr/include/readline/readline.h:493:52: note: expected 'char * (*)(const char *, int)' but argument is of type 'char * (*)(void)'
      493 | extern char **rl_completion_matches (const char *, rl_compentry_func_t *);
	  |                                                    ^~~~~~~~~~~~~~~~~~~~~
    ../or1ksim/sim-cmd.c:786:7: note: 'command_generator' declared here
      786 | char *command_generator ();
	  |       ^~~~~~~~~~~~~~~~~
    ../or1ksim/sim-cmd.c: At top level:
    ../or1ksim/sim-cmd.c:829:1: error: conflicting types for 'command_generator'; have 'char *(char *, int)'
      829 | command_generator (char *text, int state)
	  | ^~~~~~~~~~~~~~~~~
    ../or1ksim/sim-cmd.c:786:7: note: previous declaration of 'command_generator' with type 'char *(void)'
      786 | char *command_generator ();
	  |       ^~~~~~~~~~~~~~~~~

Fix by using the proper signature in the declaration.