argtable2: Fix stringop-overflow errors in arg_cat
GCC 15.0.1 is reporting the below errors when building or1ksim:

    In function 'arg_cat',
	inlined from 'arg_cat_option' at ../../argtable2/argtable2.c:655:13,
	inlined from 'arg_print_syntax' at ../../argtable2/argtable2.c:829:9:
    ../../argtable2/argtable2.c:591:10: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
      591 |     *dest=0;
	  |     ~~~~~^~
    ../../argtable2/argtable2.c: In function 'arg_print_syntax':
    ../../argtable2/argtable2.c:819:14: note: at offset 200 into destination object 'syntax' of size 200
      819 |         char syntax[200]="";
	  |              ^~~~~~
    In function 'arg_cat',
	inlined from 'arg_cat_option' at ../../argtable2/argtable2.c:654:13,
	inlined from 'arg_print_syntax' at ../../argtable2/argtable2.c:829:9:
    ../../argtable2/argtable2.c:591:10: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
      591 |     *dest=0;
	  |     ~~~~~^~

This is caused by the arg_cat function which may overrun the end of the
buffer.  Fix this by replacing the home grown arg_cat function with
libc's strlcat.